#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-rsample
Version  : 0.0.9
Release  : 30
URL      : https://cran.r-project.org/src/contrib/rsample_0.0.9.tar.gz
Source0  : https://cran.r-project.org/src/contrib/rsample_0.0.9.tar.gz
Summary  : General Resampling Infrastructure
Group    : Development/Tools
License  : GPL-2.0
Requires: R-broom
Requires: R-dplyr
Requires: R-ellipsis
Requires: R-furrr
Requires: R-generics
Requires: R-ggplot2
Requires: R-modeldata
Requires: R-purrr
Requires: R-rlang
Requires: R-slider
Requires: R-tibble
Requires: R-tidyr
Requires: R-tidyselect
Requires: R-vctrs
BuildRequires : R-broom
BuildRequires : R-dplyr
BuildRequires : R-ellipsis
BuildRequires : R-furrr
BuildRequires : R-generics
BuildRequires : R-ggplot2
BuildRequires : R-modeldata
BuildRequires : R-purrr
BuildRequires : R-rlang
BuildRequires : R-slider
BuildRequires : R-tibble
BuildRequires : R-tidyr
BuildRequires : R-tidyselect
BuildRequires : R-vctrs
BuildRequires : buildreq-R

%description
No detailed description available

%prep
%setup -q -c -n rsample
cd %{_builddir}/rsample

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1613661194

%install
export SOURCE_DATE_EPOCH=1613661194
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library rsample
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library rsample
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library rsample
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc rsample || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/rsample/DESCRIPTION
/usr/lib64/R/library/rsample/INDEX
/usr/lib64/R/library/rsample/Meta/Rd.rds
/usr/lib64/R/library/rsample/Meta/features.rds
/usr/lib64/R/library/rsample/Meta/hsearch.rds
/usr/lib64/R/library/rsample/Meta/links.rds
/usr/lib64/R/library/rsample/Meta/nsInfo.rds
/usr/lib64/R/library/rsample/Meta/package.rds
/usr/lib64/R/library/rsample/Meta/vignette.rds
/usr/lib64/R/library/rsample/NAMESPACE
/usr/lib64/R/library/rsample/NEWS.md
/usr/lib64/R/library/rsample/R/rsample
/usr/lib64/R/library/rsample/R/rsample.rdb
/usr/lib64/R/library/rsample/R/rsample.rdx
/usr/lib64/R/library/rsample/doc/Working_with_rsets.R
/usr/lib64/R/library/rsample/doc/Working_with_rsets.Rmd
/usr/lib64/R/library/rsample/doc/Working_with_rsets.html
/usr/lib64/R/library/rsample/doc/index.html
/usr/lib64/R/library/rsample/doc/rsample.R
/usr/lib64/R/library/rsample/doc/rsample.Rmd
/usr/lib64/R/library/rsample/doc/rsample.html
/usr/lib64/R/library/rsample/help/AnIndex
/usr/lib64/R/library/rsample/help/aliases.rds
/usr/lib64/R/library/rsample/help/figures/logo.png
/usr/lib64/R/library/rsample/help/paths.rds
/usr/lib64/R/library/rsample/help/rsample.rdb
/usr/lib64/R/library/rsample/help/rsample.rdx
/usr/lib64/R/library/rsample/html/00Index.html
/usr/lib64/R/library/rsample/html/R.css
/usr/lib64/R/library/rsample/tests/testthat.R
/usr/lib64/R/library/rsample/tests/testthat/helper-s3.R
/usr/lib64/R/library/rsample/tests/testthat/print_test_output/obj_sum
/usr/lib64/R/library/rsample/tests/testthat/print_test_output/rsplit
/usr/lib64/R/library/rsample/tests/testthat/print_test_output/val_split
/usr/lib64/R/library/rsample/tests/testthat/test-compat-dplyr-old.R
/usr/lib64/R/library/rsample/tests/testthat/test-compat-dplyr.R
/usr/lib64/R/library/rsample/tests/testthat/test-compat-vctrs.R
/usr/lib64/R/library/rsample/tests/testthat/test-make-splits.R
/usr/lib64/R/library/rsample/tests/testthat/test-manual.R
/usr/lib64/R/library/rsample/tests/testthat/test-print-groups.txt
/usr/lib64/R/library/rsample/tests/testthat/test-rset.R
/usr/lib64/R/library/rsample/tests/testthat/test-slide.R
/usr/lib64/R/library/rsample/tests/testthat/test_boot.R
/usr/lib64/R/library/rsample/tests/testthat/test_bootci.R
/usr/lib64/R/library/rsample/tests/testthat/test_caret.R
/usr/lib64/R/library/rsample/tests/testthat/test_fingerprint.R
/usr/lib64/R/library/rsample/tests/testthat/test_for_pred.R
/usr/lib64/R/library/rsample/tests/testthat/test_gather.R
/usr/lib64/R/library/rsample/tests/testthat/test_group.R
/usr/lib64/R/library/rsample/tests/testthat/test_initial.R
/usr/lib64/R/library/rsample/tests/testthat/test_labels.R
/usr/lib64/R/library/rsample/tests/testthat/test_loo.R
/usr/lib64/R/library/rsample/tests/testthat/test_mc.R
/usr/lib64/R/library/rsample/tests/testthat/test_names.R
/usr/lib64/R/library/rsample/tests/testthat/test_nesting.R
/usr/lib64/R/library/rsample/tests/testthat/test_permutations.R
/usr/lib64/R/library/rsample/tests/testthat/test_rolling.R
/usr/lib64/R/library/rsample/tests/testthat/test_rset.R
/usr/lib64/R/library/rsample/tests/testthat/test_rsplit.R
/usr/lib64/R/library/rsample/tests/testthat/test_strata.R
/usr/lib64/R/library/rsample/tests/testthat/test_tidy.R
/usr/lib64/R/library/rsample/tests/testthat/test_validation.R
/usr/lib64/R/library/rsample/tests/testthat/test_vfold.R
